import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { INDICATORS, DIMENSION_META, DIMENSION_ORDER } from "@/lib/sppi/indicators";
import type { ClassificationBand, IndicatorCode } from "@/lib/sppi/types";

const styles = StyleSheet.create({
  page: { padding: 36, fontSize: 10, fontFamily: "Helvetica" },
  title: { fontSize: 18, fontWeight: 700, marginBottom: 2 },
  subtitle: { fontSize: 10, color: "#475569", marginBottom: 16 },
  scoreRow: { flexDirection: "row", alignItems: "center", marginBottom: 12, gap: 16 },
  scoreBox: { fontSize: 32, fontWeight: 700 },
  bandBadge: { fontSize: 12, fontWeight: 700, padding: "4 10", borderRadius: 4, color: "white" },
  section: { marginTop: 16, marginBottom: 6, fontSize: 12, fontWeight: 700, borderBottom: "1 solid #cbd5e1", paddingBottom: 2 },
  row: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 3, borderBottom: "0.5 solid #e2e8f0" },
  label: { color: "#334155" },
  value: { fontWeight: 700 },
  footer: { position: "absolute", bottom: 24, left: 36, right: 36, fontSize: 8, color: "#94a3b8" },
});

const BAND_COLOR: Record<ClassificationBand, string> = {
  VERY_LOW: "#dc2626",
  LOW: "#f97316",
  MODERATE: "#eab308",
  HIGH: "#22c55e",
  VERY_HIGH: "#0ea5e9",
};

const BAND_LABEL: Record<ClassificationBand, string> = {
  VERY_LOW: "Very Low",
  LOW: "Low",
  MODERATE: "Moderate",
  HIGH: "High",
  VERY_HIGH: "Very High",
};

export interface ResultDocumentProps {
  projectName: string;
  region: string;
  cycleLabel: string;
  assessorName: string;
  computedAt: string;
  weightConfigName: string;
  dScoreM: number;
  dScoreK: number;
  dScoreS: number;
  sppiScore: number;
  band: ClassificationBand;
  weakestIndicator: IndicatorCode;
  recommendedAction: string;
  sensitivityLow: number | null;
  sensitivityHigh: number | null;
  indicators: { code: IndicatorCode; normalizedValue: number; mode: string }[];
}

export function ResultDocument(props: ResultDocumentProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>SPPI Assessment Result</Text>
        <Text style={styles.subtitle}>
          {props.projectName} ({props.region}) — Cycle {props.cycleLabel} — Assessed by {props.assessorName}
        </Text>

        <View style={styles.scoreRow}>
          <Text style={styles.scoreBox}>{props.sppiScore.toFixed(2)}</Text>
          <Text style={{ ...styles.bandBadge, backgroundColor: BAND_COLOR[props.band] }}>
            {BAND_LABEL[props.band].toUpperCase()} — {props.recommendedAction}
          </Text>
        </View>
        {props.sensitivityLow != null && props.sensitivityHigh != null && (
          <Text style={{ color: "#64748b", marginBottom: 8 }}>
            90% sensitivity interval: [{props.sensitivityLow.toFixed(2)}, {props.sensitivityHigh.toFixed(2)}]
          </Text>
        )}
        <Text style={{ color: "#dc2626", fontSize: 9, marginBottom: 8 }}>
          Provisional thresholds — band boundaries pending Stage 3 field calibration.
        </Text>

        <Text style={styles.section}>Dimension Breakdown</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Managerial</Text>
          <Text style={styles.value}>{props.dScoreM.toFixed(2)}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Agility</Text>
          <Text style={styles.value}>{props.dScoreK.toFixed(2)}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Spatial Governance</Text>
          <Text style={styles.value}>{props.dScoreS.toFixed(2)}</Text>
        </View>

        <Text style={styles.section}>Indicator Scores</Text>
        {DIMENSION_ORDER.map((dim) => (
          <View key={dim}>
            <Text style={{ marginTop: 6, fontWeight: 700, color: "#475569" }}>{DIMENSION_META[dim].nameEn}</Text>
            {props.indicators
              .filter((i) => INDICATORS[i.code].dimension === dim)
              .map((i) => (
                <View style={styles.row} key={i.code}>
                  <Text style={styles.label}>
                    {INDICATORS[i.code].nameEn} ({i.code}) {i.code === props.weakestIndicator ? " — weakest" : ""}
                  </Text>
                  <Text style={styles.value}>{i.normalizedValue.toFixed(2)}</Text>
                </View>
              ))}
          </View>
        ))}

        <Text style={styles.section}>Configuration Used</Text>
        <Text>Weight configuration: {props.weightConfigName}</Text>
        <Text>Computed at: {props.computedAt}</Text>

        <Text style={styles.footer}>
          Generated by the SPPI Assessment Application. Scores trace to the active WeightConfig recorded above;
          recomputing from the stored input scores and this configuration reproduces this result exactly.
        </Text>
      </Page>
    </Document>
  );
}
